### PR TITLE
Fix primary group

### LINKED ISSUE #165: Primary group should be edited in separate widget
The way it is right now together with other groups in a list is confusing.
Also the primary column takes up so much space just for one checkmark out of all groups.

### LINKED ISSUE #168: Changing primary group results in error
Something like: "Can't add user to group because it already is in group".

### PR DESCRIPTION
**Pull request by Kvel2D**
Closes #168
Closes #165 (didn't need separate edit widget, only a separate display widget)

This alters the "MemberOf" version of membership tab that is displayed for user objects.

Add primary group label that displays "Primary group: some group" below normal groups list. This replaces the "Primary" column (will remove in future) and is better because it's always visible.

Warn about trying to remove primary group/user. Before primary objects weren't selectable but that's confusing to user. Now they are selectable but if selection contains anything primary and remove button is pressed, the warning is opened (and remove is not performed).

Fix conflicts between changing primary group and adding/removing groups in apply(). Conflicts happened due to previously unknown fact that the server performs some add/remove operations on it's end when changing primary group. Server adds old primary group (that stopped being primary) to normal membership. Server also removes new primary group (that became primary) to normal membership. Therefore we have to update the state cache of membership according to what the server does. We also have to perform primary changes before add/remove. And finally, we have to ignore groups that became or stopped being primary in add/remove loops since server already added/removed them.

### CODE REVIEW

File: src/admc/tabs/membership_tab.cpp [hunk 1]
```diff
@@ -318,7 +352,31 @@ void MembershipTab::on_remove_button() {
         removed_values.append(dn);
     }
 
-    remove_values(removed_values);    
+    const bool any_selected_are_primary =
+    [this, removed_values]() {
+        for (const QString dn : removed_values) {
```
Comment (august-alt) [inline src/admc/tabs/membership_tab.cpp:357]: Please add & to dn.

**Review by august-alt — CHANGES_REQUESTED** [review]

**Review by august-alt — APPROVED** [review]
